TARGET := iphone:clang:latest:15.0
ARCHS := arm64e
INSTALL_TARGET_PROCESSES := SpringBoard
THEOS_PACKAGE_DIR := build-packages

DEBUG := 0
STRIP := 1

include $(THEOS)/makefiles/common.mk

TWEAK_NAME := NotchNowPlaying
NotchNowPlaying_FILES := Tweak.xm NNPState.m NNPView.m NNPController.m NNPDiagnostics.m NNPPreferences.m NNPLockStateController.m NNPDisplayController.m
NNP_SAFE_BOOT_TEST ?= 0
NNP_DEBUG_SHOW_WHILE_UNLOCKED ?= 0
NNP_ALLOW_ALL_MEDIA ?= 0
NNP_UI_SMOKE_TEST ?= 0
NNP_ENABLE_DISPLAY_ASSERTION_EXPERIMENT ?= 0
NNP_PHASE2E_ARM_AT_START ?= 0
NNP_PHASE2G_OBSERVER ?= 0
NNP_PHASE2G_ARM_AT_START ?= 0
NNP_PHASE2D2_DIAGNOSTIC ?= 0
NNP_PHASE2J_READONLY_RUNTIME ?= 0
NNP_PHASE2J_CALL_GETTERS ?= 0
NNP_ENABLE_PHASE4A_READONLY_BACKLIGHT_LOG ?= 0
NNP_COMPILE_PHASE4A_DIAGNOSTIC ?= 0
NNP_PHASE4A_CTOR_PREFERENCES_PROBE ?= 0
NNP_PHASE4A_DELAYED_TRACE_PROBE ?= 0
NNP_PHASE4A_UI_STATE_PROBE ?= 0
NNP_PHASE4A_DELAYED_NOOP_TEST ?= 0
NNP_PHASE4A_DELAYED_STATIC_BOOL_TEST ?= 0
NNP_PHASE4A_DELAYED_CFPREFERENCES_TEST ?= 0
NNP_PHASE4A_BUILD_ID ?= unknown
NNP_DIAGNOSTIC_UI_MARKER ?= 0
NNP_DIAGNOSTIC_BUILD_ID ?= unknown
NotchNowPlaying_CFLAGS := -fobjc-arc -DNNP_SAFE_BOOT_TEST=$(NNP_SAFE_BOOT_TEST) -DNNP_DEBUG_SHOW_WHILE_UNLOCKED=$(NNP_DEBUG_SHOW_WHILE_UNLOCKED) -DNNP_ALLOW_ALL_MEDIA=$(NNP_ALLOW_ALL_MEDIA) -DNNP_UI_SMOKE_TEST=$(NNP_UI_SMOKE_TEST) -DNNP_ENABLE_DISPLAY_ASSERTION_EXPERIMENT=$(NNP_ENABLE_DISPLAY_ASSERTION_EXPERIMENT) -DNNP_PHASE2E_ARM_AT_START=$(NNP_PHASE2E_ARM_AT_START) -DNNP_PHASE2G_OBSERVER=$(NNP_PHASE2G_OBSERVER) -DNNP_PHASE2G_ARM_AT_START=$(NNP_PHASE2G_ARM_AT_START) -DNNP_PHASE2D2_DIAGNOSTIC=$(NNP_PHASE2D2_DIAGNOSTIC) -DNNP_PHASE2J_READONLY_RUNTIME=$(NNP_PHASE2J_READONLY_RUNTIME) -DNNP_PHASE2J_CALL_GETTERS=$(NNP_PHASE2J_CALL_GETTERS) -DNNP_ENABLE_PHASE4A_READONLY_BACKLIGHT_LOG=$(NNP_ENABLE_PHASE4A_READONLY_BACKLIGHT_LOG) -DNNP_PHASE4A_BUILD_ID=\"$(NNP_PHASE4A_BUILD_ID)\" -fvisibility=hidden -fno-ident
NotchNowPlaying_CFLAGS += -DNNP_DIAGNOSTIC_UI_MARKER=$(NNP_DIAGNOSTIC_UI_MARKER) -DNNP_DIAGNOSTIC_BUILD_ID=\"$(NNP_DIAGNOSTIC_BUILD_ID)\"
NotchNowPlaying_CFLAGS += -DNNP_PHASE4A_CTOR_PREFERENCES_PROBE=$(NNP_PHASE4A_CTOR_PREFERENCES_PROBE) -DNNP_PHASE4A_DELAYED_TRACE_PROBE=$(NNP_PHASE4A_DELAYED_TRACE_PROBE) -DNNP_PHASE4A_UI_STATE_PROBE=$(NNP_PHASE4A_UI_STATE_PROBE) -DNNP_PHASE4A_DELAYED_NOOP_TEST=$(NNP_PHASE4A_DELAYED_NOOP_TEST) -DNNP_PHASE4A_DELAYED_STATIC_BOOL_TEST=$(NNP_PHASE4A_DELAYED_STATIC_BOOL_TEST) -DNNP_PHASE4A_DELAYED_CFPREFERENCES_TEST=$(NNP_PHASE4A_DELAYED_CFPREFERENCES_TEST)
NotchNowPlaying_LDFLAGS := -Wl,-dead_strip
NotchNowPlaying_FRAMEWORKS := UIKit

ifeq ($(NNP_SAFE_BOOT_TEST),0)
NotchNowPlaying_FILES += NNPMediaController.m
NotchNowPlaying_LDFLAGS += -Wl,-undefined,dynamic_lookup
endif

ifeq ($(NNP_ENABLE_DISPLAY_ASSERTION_EXPERIMENT),1)
NotchNowPlaying_FILES += NNPDisplayAssertionController.m
NotchNowPlaying_FRAMEWORKS += IOKit
endif

ifeq ($(NNP_PHASE2G_OBSERVER),1)
NotchNowPlaying_FILES += NNPBlankingObserver.m
endif

ifeq ($(NNP_PHASE2J_READONLY_RUNTIME),1)
NotchNowPlaying_FILES += NNPBackBoardReadOnlyDiagnostics.m
endif

ifneq ($(filter 1,$(NNP_ENABLE_PHASE4A_READONLY_BACKLIGHT_LOG) $(NNP_COMPILE_PHASE4A_DIAGNOSTIC) $(NNP_PHASE4A_UI_STATE_PROBE) $(NNP_PHASE4A_DELAYED_CFPREFERENCES_TEST) $(NNP_PHASE4A_DELAYED_TRACE_PROBE)),)
NotchNowPlaying_FILES += NNPPhase4AReadOnlyBacklight.m
endif


include $(THEOS_MAKE_PATH)/tweak.mk
