#import <Foundation/Foundation.h>

FOUNDATION_EXPORT void NNPNotificationDiagnosticsStart(void);
FOUNDATION_EXPORT void NNPNotificationDiagnosticsSetDisplayState(BOOL locked, BOOL aodActive);
FOUNDATION_EXPORT BOOL NNPNotificationDiagnosticsIsNotificationBacklightSource(NSInteger source);
FOUNDATION_EXPORT BOOL NNPNotificationDiagnosticsConsumeWakeForSnakeAnimation(NSInteger state, NSInteger source);
FOUNDATION_EXPORT NSDictionary *NNPNotificationDiagnosticsConsumePendingPresentationPayload(void);
